syntax on
filetype plugin indent on

colorscheme elflord

set laststatus=2
set timeoutlen=50
set cursorline
set list!
set listchars=trail:~
set number
set relativenumber
set shiftwidth=2
let &colorcolumn=join(range(81,999), ",")
