syntax on
filetype plugin indent on

let g:seoul256_background = 234
let g:airline_powerline_fonts = 1

colorscheme seoul256

set laststatus=2
set timeoutlen=50
set cursorline
set list!
set listchars=trail:~
set number
set relativenumber
set shiftwidth=2
let &colorcolumn=join(range(81,999), ",")
